# Model

In this notebook we’ll show some modeling examples with UrbanMapper.

In [1]:
import urban_mapper as um
from urban_mapper.pipeline import UrbanPipeline

# Start UrbanMapper
mapper = um.UrbanMapper()

## Preparing data

First, let’s grab some taxi data and set up a street intersections layer for Manhattan.

Note that:

- Loader example can be seen in `examples/Basics/loader.ipynb`
- Urban Layer example can be seen in `examples/Basics/urban_layer.ipynb`
- Imputer example can be seen in `examples/Basics/imputer.ipynb`

In [2]:
#Layer from Manhattan
urban_layer = (
    mapper.urban_layer.with_type("streets_intersections")
    .from_place("Downtown, Brooklyn, New York, USA", network_type="drive")
    .build()
)

#Taxi data
taxi_data = (
  mapper
  .loader
  .from_huggingface("oscur/taxisvis1M", number_of_rows=5000)
  .with_columns("pickup_longitude", "pickup_latitude")
  .load()
)
taxi_data['pickup_longitude'] = taxi_data['pickup_longitude'].astype(float)
taxi_data['pickup_latitude'] = taxi_data['pickup_latitude'].astype(float)

#Imputer
imputed_data = (
  mapper
  .imputer
  .with_type("SimpleGeoImputer")
  .on_columns("pickup_longitude", "pickup_latitude")
  .transform(taxi_data, urban_layer)
)

#Filter
filtered_data = mapper.filter.with_type("BoundingBoxFilter").transform(imputed_data, urban_layer)

#Mapping data into layer
_, mapped_data = urban_layer.map_nearest_layer(filtered_data, longitude_column="pickup_longitude", latitude_column="pickup_latitude", output_column="pickup_segment")

#Some enrichments used as information for prediction
enricher1 = mapper.enricher.with_data(group_by="pickup_segment").count_by(output_column="pickup_count").build()
enricher2 = mapper.enricher.with_data(group_by="pickup_segment", values_from="total_amount").aggregate_by(method="sum", output_column="sum_amount").build()
enricher3 = mapper.enricher.with_data(group_by="pickup_segment", values_from="trip_distance").aggregate_by(method="mean", output_column="avg_distance").build()
enricher4 = mapper.enricher.with_data(group_by="pickup_segment", values_from="passenger_count").aggregate_by(method="mean", output_column="passenger_avg").build()
enricher5 = mapper.enricher.with_data(group_by="pickup_segment", values_from="payment_type").aggregate_by(method="mode", output_column="payment_type_mode").build()

enriched_layer = enricher1.enrich(mapped_data, urban_layer)
enriched_layer = enricher2.enrich(mapped_data, enriched_layer)
enriched_layer = enricher3.enrich(mapped_data, enriched_layer)
enriched_layer = enricher4.enrich(mapped_data, enriched_layer)
enriched_layer = enricher5.enrich(mapped_data, enriched_layer)

## Model configuration

### 1. Clustering

In [3]:
## Default clustering method: KMeans
model = (
    mapper
    .model
## When no target column is defined in `with_columns` method, the model factory tries a clustering method by default
## The user can also define a clustering algorithm by setting up the model name/object    
#    .with_model(<model name/object from scikitlearn>)
    .build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data

,osmid,y,x,highway,street_count,geometry,pickup_count,sum_amount,avg_distance,passenger_avg,payment_type_mode,subset,cluster_predicted
0,42464631,40.692056,-73.982623,traffic_signals,4,POINT (-73.98262 40.69206),17,240.22,3.075882,1.941176,1,train,0
1,42464823,40.692170,-73.989126,traffic_signals,4,POINT (-73.98913 40.69217),6,62.70,1.711667,1.833333,1,train,0
2,42464824,40.691802,-73.988213,traffic_signals,4,POINT (-73.98821 40.6918),0,0.00,0.000000,0.000000,0,train,3
3,42464827,40.691455,-73.987339,traffic_signals,4,POINT (-73.98734 40.69145),34,469.65,2.784706,1.264706,1,train,0
4,42464832,40.690663,-73.985353,traffic_signals,3,POINT (-73.98535 40.69066),0,0.00,0.000000,0.000000,0,train,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,9664385497,40.694956,-73.988947,crossing,3,POINT (-73.98895 40.69496),1,26.80,9.040000,1.000000,2,train,1
73,10001058440,40.694936,-73.988697,NaN,3,POINT (-73.9887 40.69494),3,43.40,3.033333,1.333333,2,train,1
74,11381945329,40.695257,-73.988681,NaN,3,POINT (-73.98868 40.69526),9,171.28,4.255556,1.555556,1,train,1
75,11381945330,40.696111,-73.988586,NaN,4,POINT (-73.98859 40.69611),11,177.21,3.638182,1.090909,1,train,1
76,13086792482,40.688949,-73.980971,NaN,3,POINT (-73.98097 40.68895),49,827.21,3.471224,1.591837,1,train,1

### 2. Classification

In [4]:
## Default classification method: SVM 
model = (
    mapper
    .model
## When an INTEGER target column is defined in `with_columns` method, the model factory tries a classifier method by default
    .with_columns(target_column="payment_type_mode")
## The user can also define a classification algorithm by setting up the model name/object    
#    .with_model(<model name/object from scikitlearn>)
    .build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data

,osmid,y,x,highway,street_count,geometry,pickup_count,sum_amount,avg_distance,passenger_avg,payment_type_mode,subset,payment_type_mode_predicted
0,42464631,40.692056,-73.982623,traffic_signals,4,POINT (-73.98262 40.69206),17,240.22,3.075882,1.941176,1,test,1
1,42464823,40.692170,-73.989126,traffic_signals,4,POINT (-73.98913 40.69217),6,62.70,1.711667,1.833333,1,train,1
2,42464824,40.691802,-73.988213,traffic_signals,4,POINT (-73.98821 40.6918),0,0.00,0.000000,0.000000,0,train,0
3,42464827,40.691455,-73.987339,traffic_signals,4,POINT (-73.98734 40.69145),34,469.65,2.784706,1.264706,1,train,1
4,42464832,40.690663,-73.985353,traffic_signals,3,POINT (-73.98535 40.69066),0,0.00,0.000000,0.000000,0,test,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,9664385497,40.694956,-73.988947,crossing,3,POINT (-73.98895 40.69496),1,26.80,9.040000,1.000000,2,train,2
73,10001058440,40.694936,-73.988697,NaN,3,POINT (-73.9887 40.69494),3,43.40,3.033333,1.333333,2,train,1
74,11381945329,40.695257,-73.988681,NaN,3,POINT (-73.98868 40.69526),9,171.28,4.255556,1.555556,1,train,1
75,11381945330,40.696111,-73.988586,NaN,4,POINT (-73.98859 40.69611),11,177.21,3.638182,1.090909,1,train,1
76,13086792482,40.688949,-73.980971,NaN,3,POINT (-73.98097 40.68895),49,827.21,3.471224,1.591837,1,train,1

### 3. Regression

  - if longitude_column/latitude_column are defined: `RegressionKriging` from the `pykrige` library
  - if geometry_column is defined or no column is defined but the dataset has a geometry: `ML_Lag` from the `spreg` library (part of the `pysal` library)
  - otherwise, SVR from scikit-learn

In [5]:
## Defining longitude_column/latitude_column
model = (
    mapper
    .model
## When a FLOAT `target_column` is defined in `with_columns` method, the model factory tries a regression method by default
    .with_columns(target_column="sum_amount", longitude_column="x", latitude_column="y")
## The user can also define a regression algorithm by setting up the model name/object    
#    .with_model(<model name/object from scikitlearn>)
    .build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data

Finished learning regression model
Finished kriging residuals

,osmid,y,x,highway,street_count,geometry,pickup_count,sum_amount,avg_distance,passenger_avg,payment_type_mode,subset,sum_amount_predicted
0,42464631,40.692056,-73.982623,traffic_signals,4,POINT (-73.98262 40.69206),17,240.22,3.075882,1.941176,1,test,291.282736
1,42464823,40.692170,-73.989126,traffic_signals,4,POINT (-73.98913 40.69217),6,62.70,1.711667,1.833333,1,train,62.700000
2,42464824,40.691802,-73.988213,traffic_signals,4,POINT (-73.98821 40.6918),0,0.00,0.000000,0.000000,0,train,0.000000
3,42464827,40.691455,-73.987339,traffic_signals,4,POINT (-73.98734 40.69145),34,469.65,2.784706,1.264706,1,train,469.650000
4,42464832,40.690663,-73.985353,traffic_signals,3,POINT (-73.98535 40.69066),0,0.00,0.000000,0.000000,0,test,15.403679
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,9664385497,40.694956,-73.988947,crossing,3,POINT (-73.98895 40.69496),1,26.80,9.040000,1.000000,2,train,26.800000
73,10001058440,40.694936,-73.988697,NaN,3,POINT (-73.9887 40.69494),3,43.40,3.033333,1.333333,2,train,43.400000
74,11381945329,40.695257,-73.988681,NaN,3,POINT (-73.98868 40.69526),9,171.28,4.255556,1.555556,1,train,171.280000
75,11381945330,40.696111,-73.988586,NaN,4,POINT (-73.98859 40.69611),11,177.21,3.638182,1.090909,1,train,177.210000
76,13086792482,40.688949,-73.980971,NaN,3,POINT (-73.98097 40.68895),49,827.21,3.471224,1.591837,1,NaN,NaN

In [6]:
## Defining geometry_column
model = (
    mapper
    .model
## When a FLOAT `target_column` is defined in `with_columns` method, the model factory tries a regression method by default
    .with_columns(target_column="sum_amount", geometry_column="geometry")
## The user can also define a regression algorithm by setting up the model name/object    
#    .with_model(<model name/object from scikitlearn>)
    .build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data

,osmid,y,x,highway,street_count,geometry,pickup_count,sum_amount,avg_distance,passenger_avg,payment_type_mode,subset,sum_amount_predicted
0,42464631,40.692056,-73.982623,traffic_signals,4,POINT (-73.98262 40.69206),17,240.22,3.075882,1.941176,1,test,268.737957
1,42464823,40.692170,-73.989126,traffic_signals,4,POINT (-73.98913 40.69217),6,62.70,1.711667,1.833333,1,train,97.296818
2,42464824,40.691802,-73.988213,traffic_signals,4,POINT (-73.98821 40.6918),0,0.00,0.000000,0.000000,0,train,-17.575872
3,42464827,40.691455,-73.987339,traffic_signals,4,POINT (-73.98734 40.69145),34,469.65,2.784706,1.264706,1,train,522.111110
4,42464832,40.690663,-73.985353,traffic_signals,3,POINT (-73.98535 40.69066),0,0.00,0.000000,0.000000,0,test,3.542355
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,9664385497,40.694956,-73.988947,crossing,3,POINT (-73.98895 40.69496),1,26.80,9.040000,1.000000,2,train,70.048421
73,10001058440,40.694936,-73.988697,NaN,3,POINT (-73.9887 40.69494),3,43.40,3.033333,1.333333,2,train,39.673571
74,11381945329,40.695257,-73.988681,NaN,3,POINT (-73.98868 40.69526),9,171.28,4.255556,1.555556,1,train,155.978369
75,11381945330,40.696111,-73.988586,NaN,4,POINT (-73.98859 40.69611),11,177.21,3.638182,1.090909,1,train,180.013113
76,13086792482,40.688949,-73.980971,NaN,3,POINT (-73.98097 40.68895),49,827.21,3.471224,1.591837,1,NaN,NaN

In [7]:
## No coordinate column defined in a simple dataframe
model = (
    mapper
    .model
## When a FLOAT `target_column` is defined in `with_columns` method, the model factory tries a regression method by default
    .with_columns(target_column="sum_amount")
## The user can also define a regression algorithm by setting up the model name/object    
#    .with_model(<model name/object from scikitlearn>)
    .build()
)    

data_without_geo = enriched_layer.layer.drop("geometry", axis = 1)
predicted_data = model.fit_predict(data_without_geo)
predicted_data

,osmid,y,x,highway,street_count,pickup_count,sum_amount,avg_distance,passenger_avg,payment_type_mode,subset,sum_amount_predicted
0,42464631,40.692056,-73.982623,traffic_signals,4,17,240.22,3.075882,1.941176,1,test,299.203156
1,42464823,40.692170,-73.989126,traffic_signals,4,6,62.70,1.711667,1.833333,1,train,77.796244
2,42464824,40.691802,-73.988213,traffic_signals,4,0,0.00,0.000000,0.000000,0,train,15.198482
3,42464827,40.691455,-73.987339,traffic_signals,4,34,469.65,2.784706,1.264706,1,train,454.516914
4,42464832,40.690663,-73.985353,traffic_signals,3,0,0.00,0.000000,0.000000,0,test,15.196402
...,...,...,...,...,...,...,...,...,...,...,...,...
72,9664385497,40.694956,-73.988947,crossing,3,1,26.80,9.040000,1.000000,2,train,41.966467
73,10001058440,40.694936,-73.988697,NaN,3,3,43.40,3.033333,1.333333,2,train,58.505573
74,11381945329,40.695257,-73.988681,NaN,3,9,171.28,4.255556,1.555556,1,train,156.137187
75,11381945330,40.696111,-73.988586,NaN,4,11,177.21,3.638182,1.090909,1,train,162.058383
76,13086792482,40.688949,-73.980971,NaN,3,49,827.21,3.471224,1.591837,1,NaN,NaN

### 4. Other basic configurations

In [8]:
from sklearn.preprocessing import MinMaxScaler
from urban_mapper.modules.model import ThresholdOutlierDetector

## Defining transformations
model = (
    mapper
    .model
## When a FLOAT `target_column` is defined in `with_columns` method, the model factory tries a regression method by default
    .with_columns(target_column="sum_amount", geometry_column="geometry")
    .with_transform(feature_selector = None, ## default VarianceThreshold(0.01)
                    feature_scaler = MinMaxScaler(),   ## default StandardScaler()

                    ## applied only on REGRESSION tasks
                    target_filter = ThresholdOutlierDetector(upper = 500),  ## default utils.IQROutlierDetector()
                    target_scaler = MinMaxScaler(),  ## default StandardScaler()

                    ## applied only on CLASSIFICATION tasks
                    target_encoder = None, ## default LabelEncoder()
    ).build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data

,osmid,y,x,highway,street_count,geometry,pickup_count,sum_amount,avg_distance,passenger_avg,payment_type_mode,subset,sum_amount_predicted
0,42464631,40.692056,-73.982623,traffic_signals,4,POINT (-73.98262 40.69206),17,240.22,3.075882,1.941176,1,test,271.575797
1,42464823,40.692170,-73.989126,traffic_signals,4,POINT (-73.98913 40.69217),6,62.70,1.711667,1.833333,1,train,98.410155
2,42464824,40.691802,-73.988213,traffic_signals,4,POINT (-73.98821 40.6918),0,0.00,0.000000,0.000000,0,train,-8.885883
3,42464827,40.691455,-73.987339,traffic_signals,4,POINT (-73.98734 40.69145),34,469.65,2.784706,1.264706,1,train,520.089847
4,42464832,40.690663,-73.985353,traffic_signals,3,POINT (-73.98535 40.69066),0,0.00,0.000000,0.000000,0,test,-0.558402
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,9664385497,40.694956,-73.988947,crossing,3,POINT (-73.98895 40.69496),1,26.80,9.040000,1.000000,2,train,72.370106
73,10001058440,40.694936,-73.988697,NaN,3,POINT (-73.9887 40.69494),3,43.40,3.033333,1.333333,2,train,44.359816
74,11381945329,40.695257,-73.988681,NaN,3,POINT (-73.98868 40.69526),9,171.28,4.255556,1.555556,1,train,160.519131
75,11381945330,40.696111,-73.988586,NaN,4,POINT (-73.98859 40.69611),11,177.21,3.638182,1.090909,1,train,182.717311
76,13086792482,40.688949,-73.980971,NaN,3,POINT (-73.98097 40.68895),49,827.21,3.471224,1.591837,1,NaN,NaN

In [9]:
## Defining data proportion train:validation:test
## UM model already splits data into 90:10 (train:test) split byt default
model = (
    mapper
    .model
## When a FLOAT `target_column` is defined in `with_columns` method, the model factory tries a regression method by default
    .with_columns(target_column="sum_amount", geometry_column="geometry")
    .with_data(train_size = 0.8, 
               validation_size = None,   
               test_size = 0.2,  ## default 0.1
    ).build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data

,osmid,y,x,highway,street_count,geometry,pickup_count,sum_amount,avg_distance,passenger_avg,payment_type_mode,subset,sum_amount_predicted
0,42464631,40.692056,-73.982623,traffic_signals,4,POINT (-73.98262 40.69206),17,240.22,3.075882,1.941176,1,test,274.735785
1,42464823,40.692170,-73.989126,traffic_signals,4,POINT (-73.98913 40.69217),6,62.70,1.711667,1.833333,1,train,102.665439
2,42464824,40.691802,-73.988213,traffic_signals,4,POINT (-73.98821 40.6918),0,0.00,0.000000,0.000000,0,train,7.487985
3,42464827,40.691455,-73.987339,traffic_signals,4,POINT (-73.98734 40.69145),34,469.65,2.784706,1.264706,1,train,517.432661
4,42464832,40.690663,-73.985353,traffic_signals,3,POINT (-73.98535 40.69066),0,0.00,0.000000,0.000000,0,test,-8.414808
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,9664385497,40.694956,-73.988947,crossing,3,POINT (-73.98895 40.69496),1,26.80,9.040000,1.000000,2,train,65.326787
73,10001058440,40.694936,-73.988697,NaN,3,POINT (-73.9887 40.69494),3,43.40,3.033333,1.333333,2,train,39.312922
74,11381945329,40.695257,-73.988681,NaN,3,POINT (-73.98868 40.69526),9,171.28,4.255556,1.555556,1,test,148.308972
75,11381945330,40.696111,-73.988586,NaN,4,POINT (-73.98859 40.69611),11,177.21,3.638182,1.090909,1,train,179.543487
76,13086792482,40.688949,-73.980971,NaN,3,POINT (-73.98097 40.68895),49,827.21,3.471224,1.591837,1,NaN,NaN

### 5. Custom model

1. Reimplement the class CustomModel_Adapter combined with scikitlearn RegressorMixin, ClassifierMixin, or ClusterMixin
2. Beyond `X`, `y` arguments of fit/predict, `kwargs` can have `long_lat`, `geometry`. 
   When the user defines a `validation_size` in `with_data` method, it also has `validation`, `validation_target`, `validation_long_lat`, and `validation_geometry`

In [10]:
## Testing a PyTorch MLP regressor

import torch
import torch.nn as nn
import numpy as np
import tqdm

from torch.utils.data import DataLoader

from urban_mapper.modules.model import CustomModel_Adapter
from sklearn.base import RegressorMixin

## An adapter that has and fit (train) a PyTorch MLP a call it for predictions
class MyRegressor(RegressorMixin, CustomModel_Adapter):
  def __init__(self):
    self.model = None
    self.epochs = 100
    self.batch_size = 25
    self.loss_func = torch.nn.MSELoss() 
    self.optimizer = None

  def fit(self, X, y, **kwargs):
    if self.model is None:
      self.model = SimpleMLP(num_feat=X.shape[1], num_output=1)
      self.model.to("cpu")

    train_loader = DataLoader(MyDataset(X, y), batch_size=self.batch_size, shuffle= True, drop_last = False) 
    self.optimizer = torch.optim.Adam(self.model.parameters(), lr=0.0001, weight_decay=0.0)

    progress = tqdm.tqdm(total = self.epochs, desc = "Epoch ", bar_format='{desc}|{bar:50}| {n_fmt}/{total_fmt} [{elapsed}<{remaining} - {rate_fmt}]{postfix}')
    train_loss = []
    validation_loss = []

    for epoch in range(1, self.epochs + 1):
      self.model.train()

      batch_train_loss = 0

      ##Running model over the training subset 
      for X_train, y_train in train_loader:
        y_train_pred = self.model(X_train)

        loss = self.loss_func(y_train_pred, y_train.float().to(y_train_pred.device))
        batch_train_loss += loss.detach().cpu().item()

        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

      train_loss.append(batch_train_loss / len(train_loader))

      ##Running model over the validation subset
      with torch.no_grad():
        if "validation" in kwargs:
          self.model.eval()
          validation = MyDataset(kwargs["validation"], kwargs["validation_target"]) 

          y_val_pred = self.model(validation.data)

          loss = self.loss_func(y_val_pred, validation.label.float().to(y_train_pred.device))
          validation_loss.append(loss.detach().cpu().item())

      progress.update(1)
      progress.set_postfix( {"loss": np.mean(train_loss), "val loss": np.mean(validation_loss) } )

    progress.close()

    ##Saving best model and evaluation
    return self

  def predict(self, X, **kwargs):
    if self.model is not None:
      X = torch.from_numpy(np.array(X)).to(torch.float32)
      return self.model(X).detach().cpu().numpy()

  def load(self, path):
    pass

## A PyTorch MLP model
class SimpleMLP(nn.Module):
  def __init__(self, num_feat, num_output):
    super(SimpleMLP, self).__init__()

    self.projection_size = 128

    self._device = nn.Parameter(torch.empty(0))
    self.hidden_layers = nn.ModuleList([
      nn.Linear(num_feat, 128),
      nn.Linear(128, 256),
      nn.Linear(256, self.projection_size),
      nn.Dropout(0.5)
    ])      
    self.head = nn.Linear(self.projection_size, num_output)

  def forward(self, X):
    x = X.to(self._device.device)

    for layer in self.hidden_layers:
      x = layer(x)

      if isinstance(layer, nn.Linear):
        x = x.relu()

    out = self.head(x)
    return out.sigmoid()  

## An simple PyTorch dataset helper
class MyDataset(torch.utils.data.Dataset):
  def __init__(self, x, y):
    self.data = torch.from_numpy(np.array(x)).to(torch.float32)
    self.label = torch.from_numpy(np.array(y)).to(torch.float32).reshape(-1, 1)    

  def __getitem__(self, index):    
    return self.data[index], self.label[index]
  
  def __len__(self):
    return len(self.data)

In [11]:
## Using the custom model
model = (
    mapper
    .model
    .with_model(MyRegressor())
## When a FLOAT `target_column` is defined in `with_columns` method, the model factory tries a regression method by default
    .with_columns(target_column="sum_amount")
    .with_data(validation_size = 0.1)
    .build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data

Epoch |██████████████████████████████████████████████████| 100/100 [00:01<00:00 - 50.69it/s], loss=0.8, val loss=3.1e+4

,osmid,y,x,highway,street_count,geometry,pickup_count,sum_amount,avg_distance,passenger_avg,payment_type_mode,subset,sum_amount_predicted
0,42464631,40.692056,-73.982623,traffic_signals,4,POINT (-73.98262 40.69206),17,240.22,3.075882,1.941176,1,test,283.786774
1,42464823,40.692170,-73.989126,traffic_signals,4,POINT (-73.98913 40.69217),6,62.70,1.711667,1.833333,1,train,163.568680
2,42464824,40.691802,-73.988213,traffic_signals,4,POINT (-73.98821 40.6918),0,0.00,0.000000,0.000000,0,train,156.078384
3,42464827,40.691455,-73.987339,traffic_signals,4,POINT (-73.98734 40.69145),34,469.65,2.784706,1.264706,1,train,328.299347
4,42464832,40.690663,-73.985353,traffic_signals,3,POINT (-73.98535 40.69066),0,0.00,0.000000,0.000000,0,test,156.131073
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,9664385497,40.694956,-73.988947,crossing,3,POINT (-73.98895 40.69496),1,26.80,9.040000,1.000000,2,validation,161.199905
73,10001058440,40.694936,-73.988697,NaN,3,POINT (-73.9887 40.69494),3,43.40,3.033333,1.333333,2,validation,164.446030
74,11381945329,40.695257,-73.988681,NaN,3,POINT (-73.98868 40.69526),9,171.28,4.255556,1.555556,1,train,186.314636
75,11381945330,40.696111,-73.988586,NaN,4,POINT (-73.98859 40.69611),11,177.21,3.638182,1.090909,1,train,182.308655
76,13086792482,40.688949,-73.980971,NaN,3,POINT (-73.98097 40.68895),49,827.21,3.471224,1.591837,1,train,333.498871

### 6. Using Pipeline

The user can also use a `scikitlearn Pipeline`. In this case, `with_transform` and `with_data` method configurations will be ignored to use only the pipeline steps.
Besides, only `target_column` argument of `with_columns` will be used.

Thefore, `mapper.model` works as an adapter for the `UrbanMapper` structure.

In [3]:
from sklearn.preprocessing import  MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.compose import TransformedTargetRegressor, ColumnTransformer, make_column_selector

## Simple pipeline for regression with: feature scaling - only of numeric features, and regressor with target scaling
pipeline = Pipeline([
    ("feature_scaler", ColumnTransformer([
       ("selector", MinMaxScaler(), make_column_selector(dtype_include="number"))
    ])),
    ("model", TransformedTargetRegressor(regressor=SVR(), transformer=MinMaxScaler()))
  ])

model = (
    mapper
    .model
## The user should pass the pipeline and define the `target_column` 
    .with_model(pipeline)
    .with_columns(target_column="sum_amount")
    .build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data

array([ 531.63554421,  387.2477214 ,  311.42855757,  601.87878609,
        256.90425907,  306.94630469,  356.94678222,  272.8005874 ,
        353.39817892,  316.46487676,  340.8597501 ,  410.99187653,
        425.92472616,  262.30750365,  393.33770347,  259.71974666,
        244.08691593,  235.40535673,  296.08940626,  583.30525661,
       2035.36214044,  364.66744352,  637.32827568,  358.28517749,
        460.74505413, 1329.58806482,  478.5043987 ,  467.7704728 ,
        287.82345272,  527.04933327,  357.5954659 ,  509.89853106,
        576.75283481,  407.69763968,  370.98865324,  502.81209091,
        470.73929404,  345.48151023,  325.8160642 ,  339.93764831,
        368.06433169,  412.87415134,  351.95781911,  324.70416593,
        887.36072537,  618.58400005,  927.53657335,  559.22893748,
        330.64610646,  338.43147469,  329.15109267,  284.47762317,
        343.40514344,  566.30685996,  330.77321173,  444.60095091,
        571.9826525 , 1263.87089467,  660.4107772 ,  904.40076201,
        531.0094117 ,  386.17368293,  517.28369886,  296.58357026,
       1317.09218054,  321.0610149 , 2924.34415438,  488.77394889,
        324.59604518,  463.01946736,  523.10700031,  383.57061448,
        353.38893995,  368.60016607,  467.81267984,  503.07102952,
        851.92872258])

### 7. Beyond clustering, classification, or regression

Following `custom model` and `pipeline` use, the user can reimplement `CustomModel_Adapter` without any scikitlearn `RegressorMixin`, `ClassifierMixin`, or `ClusterMixin`

In this case, `with_transform`, `with_data`, and `with_columns` method configurations will also be ignored.
The implemented class should take care of preprocessing data and fitting its own model in the `fit` method as well as the predicitons with `prediction` method.

Thefore, `mapper.model` works as an adapter for the `UrbanMapper` structure.

In [ ]:
from urban_mapper.modules.model import CustomModel_Adapter

## An adapter
class GeneralModel(CustomModel_Adapter):
  def __init__(self):
    pass

  def fit(self, X, y, **kwargs):
    return self

  def predict(self, X, **kwargs):
    return X

  def load(self, path):
    pass

In [ ]:
## Using the custom model
model = (
    mapper
    .model
    .with_model(GeneralModel())
    .build()
)    

predicted_data = model.fit_predict(enriched_layer.layer)
predicted_data